### ISSUE TITLE
is_ordered flag is problematic?

### ISSUE THREAD

**Issue by bcen** [percolate/jsonmatch#4]
`is_ordered` controls whether the ordering matters or not, however, it does not work in some cases because sorting a list of dict is not deterministic enough with the dict to be tested for comparison because they both hold different data.

https://github.com/percolate/jsonmatch/blob/58140dedf27b4e96a7e42c0604ff82d3355372c5/jsonmatch/matcher.py#L156-L157

https://github.com/percolate/jsonmatch/blob/58140dedf27b4e96a7e42c0604ff82d3355372c5/jsonmatch/matcher.py#L206

e.g.

```python
exps = [
    {
        'id': 'test:1',
        'd': dict,
    },
    {
        'id': 'test:2',
        'd': dict,
    },
    {
        'id': 'test:3',
        'd': dict,
    },
]

tests = [
    {
        'id': 'test:1',
        'd': {'a': 1, 'b': 2},
    },
    {
        'id': 'test:2',
        'd': {'a': 2},
    },
    {
        'id': 'test:3',
        'd': {},
    },
]

jsonmatch.compile(exps).assert_matches(tests, is_ordered=False)
```

Gives

```
Expected:
[{u'd': <type 'dict'>, u'id': u'test:1'},
 {u'd': <type 'dict'>, u'id': u'test:2'},
 {u'd': <type 'dict'>, u'id': u'test:3'}]

Got:
[{u'd': {u'a': 1, u'b': 2}, u'id': u'test:1'},
 {u'd': {u'a': 2}, u'id': u'test:2'},
 {u'd': {}, u'id': u'test:3'}]

Diffs:
{(0, u'id'): (u'test:1', u'test:3'), (2, u'id'): (u'test:3', u'test:1')}

Traceback (most recent call last):
  File "test.py", line 35, in <module>
    jsonmatch.compile(exps).assert_matches(tests, is_ordered=False)
  File "/Users/bcen/codes/jsonmatch/jsonmatch/matcher.py", line 61, in assert_matches
    raise AssertionError(msg)
AssertionError: Candidate dict doesn't match schema.
```

```
[{u'id': u'test:1', u'd': <type 'dict'>}, {u'id': u'test:2', u'd': <type 'dict'>}, {u'id': u'test:3', u'd': <type 'dict'>}]
[{u'id': u'test:3', u'd': {}}, {u'id': u'test:2', u'd': {u'a': 2}}, {u'id': u'test:1', u'd': {u'a': 1, u'b': 2}}]
```

**Comment by bcen** [comment]
Closing this. will workaround it.
